### ISSUE TITLE
which version of python?

### ISSUE THREAD

**Issue by ghost** [iScrE4m/Dispenser#9]
which version of python do you want this written in?

**Comment by djetelina** [comment]
At first I wanted 3.6 (when it comes out). But then I realized we might need users to actually run in themselves, which means  compatibility with 3.3+ would be nice. On the other hand, by the time this is going to be finished, 3.6 might be the stable version

**Comment by danvilar** [comment]
@iScrE4m yeah, I think it's better to play safe. But it should be python 3.3+ and not python 2.7.x

**Comment by djetelina** [comment]
No doubt about that! The reason I wanted 3.6 is because I really like type annotations and wanted to play around with them a bit more, but annotaing just functions will have to do, I can't put my preferences before users :) .

So definite answer: **3.3+**
